# from discordjs/discord-api-types
name: Publish next

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i

      - name: Bump version
        run: npx standard-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

      - name: Deprecate old versions
        run: npm deprecate @jadl/cmd@"~$(jq --raw-output '.version' package.json)-next" "No longer supported. Install the latest @next release" || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

      - name: Publish new version
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json)-next.$(git rev-parse --short HEAD).$(date +%s)
          npm publish --tag next || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}